package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"pokedex-graphql/graph/model"
)

// Create is the resolver for the Create field.
func (r *mutationResolver) Create(ctx context.Context, input model.NewPokemon) (*model.Pokemon, error) {
	if input.ID != nil {
		return nil, fmt.Errorf("id must be null")
	}
	Pokemon := model.Pokemon{
		Name:        input.Name,
		Description: input.Description,
		Category:    input.Category,
		Type:        input.Type,
		Abilities:   input.Abilities,
	}
	err := r.DB.CreatePokemon(&Pokemon)
	if err != nil {
		return nil, err
	}
	return &Pokemon, nil
}

// Update is the resolver for the Update field.
func (r *mutationResolver) Update(ctx context.Context, input model.NewPokemon) (*model.Pokemon, error) {
	if input.ID == nil {
		return nil, fmt.Errorf("id must not be null")
	}
	Pokemon := model.Pokemon{
		ID:          *input.ID,
		Name:        input.Name,
		Description: input.Description,
		Category:    input.Category,
		Type:        input.Type,
		Abilities:   input.Abilities,
	}
	_, err := r.DB.PokemonByID(*input.ID)
	if err != nil {
		return nil, err
	}

	err = r.DB.UpdatePokemon(Pokemon)
	if err != nil {
		return nil, err
	}
	return &Pokemon, nil
}

// Delete is the resolver for the Delete field.
func (r *mutationResolver) Delete(ctx context.Context, id string) (bool, error) {
	err := r.DB.DeletePokemon(id)
	if err != nil {
		return false, err
	}
	return true, nil
}

// AllPokemon is the resolver for the AllPokemon field.
func (r *queryResolver) AllPokemon(ctx context.Context) ([]*model.Pokemon, error) {
	return r.DB.AllPokemon(), nil
}

// GetPokemonByID is the resolver for the GetPokemonByID field.
func (r *queryResolver) GetPokemonByID(ctx context.Context, id string) (*model.Pokemon, error) {
	return r.DB.PokemonByID(id)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
