package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"pokedex-graphql/graph/model"
)

// Create is the resolver for the Create field.
func (r *mutationResolver) Create(ctx context.Context, input model.NewPokemon) (*model.Pokemon, error) {
	n := model.Pokemon{
		Name:        input.Name,
		Description: input.Description,
		Category:    input.Category,
		Type:        input.Type,
		Abilities:   input.Abilities,
	}
	err := r.DB.CreatePokemon(&n)
	if err != nil {
		return nil, err
	}
	return &n, nil
}

// Update is the resolver for the Update field.
func (r *mutationResolver) Update(ctx context.Context, input model.UpdatePokemon) (*model.Pokemon, error) {
	Pokemon := model.Pokemon{
		Name:        *input.Name,
		Description: *input.Description,
	}
	err := r.DB.UpdatePokemon(&Pokemon)
	if err != nil {
		return nil, err
	}
	return &Pokemon, nil
}

// Delete is the resolver for the Delete field.
func (r *mutationResolver) Delete(ctx context.Context, name string) (bool, error) {
	err := r.DB.DeletePokemon(name)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Allpokemon is the resolver for the Allpokemon field.
func (r *queryResolver) Allpokemon(ctx context.Context) ([]*model.Pokemon, error) {
	return r.DB.AllPokemon(), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
