// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPokemon struct {
	Name        *string `json:"name"`
	Description string  `json:"description"`
}

type Pokemon struct {
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	Type        []*PokemonType `json:"type"`
}

type PokemonType struct {
	Category  string    `json:"category"`
	Abilities []*string `json:"abilities"`
}
